# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  ImageName: '010994/idealfactory-v1:$(Build.BuildId)'
  HEROKU_API_KEY: $(HEROKU_API_KEY)
  HEROKU_APP_NAME: $(HEROKU_APP_NAME)  
steps:
- script: |
    # npm install -global Heroku
    # sudo snap install --classic heroku
    curl https://cli-assets.heroku.com/install.sh | sh

  displayName: 'i heroku cli'

- script: 
  workingDirectory: './my-test'
  displayName: 'working dire'
  

- script: |
    echo build the image
    docker build -t my-test .
    docker tag my-test registry.heroku.com/$APP_NAME/web
    docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    heroku container:push web -a $HEROKU_APP_NAME
    heroku container:release web -a $HEROKU_APP_NAME
   # echo CONTAINER LOGIN

   # heroku container:login

   # echo PUSH
   # heroku container:push -a $HEROKU_APP_NAME web

   # echo RELEASE
   # heroku container:release -a $HEROKU_APP_NAME web
  displayName: 'heroku push'
