pool:
  name: Azure Pipelines
steps:
- task: DotNetCoreCLI@2
  displayName: restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    vstsFeed: '1a5a0995-64b8-406c-be59-2c59328ca74e'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: publish

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'my-co'
    repository: 'robertechie/my-test'
    tags: |
     latest
     $(Build.BuildId)

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact'
